[package]
name = "rusty_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shogi = "0.12.2"
shogi_core = "0.1.5"
shogi_legality_lite = "0.1.2"
random-number = "0.1.8"
